//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Klasa.cpp
//  @ Date : 08.04.2024
//  @ Author :
//
//

#include<iostream>
using namespace std;
#include "Klasa.h"

void Klasa::setNumer(int nr) {
    this->numer = nr;
}

int Klasa::getNumer() {
    return numer;
}

void Klasa::getUczniowie() {
    for(int i = 0 ; i < uczniowie.size();i++){
        cout<<"Uczniowie w klasie "<<numer<< " :"<<"\n"<<uczniowie[i]->getImie()<<" "<<uczniowie[i]->getNazwisko()<<"\n";
    }
}

void Klasa::dodajUcznia(Uczen* uczen) {
    uczniowie.push_back(uczen);
}

void Klasa::usunUcznia(int id) {
    for(int i = 0 ; i < uczniowie.size();i++){
        if(i == id){
            uczniowie.erase(uczniowie.begin()+i);
        }
    }
}
Klasa::Klasa(int numer) {
    this->numer = numer;
}

