//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Szkola.cpp
//  @ Date : 08.04.2024
//  @ Author :
//
//
#include<vector>
#include<string>
using namespace std;
#include <iostream>
#include "Szkola.h"

void Szkola::setNazwa(string nazwa) {
    this->nazwa = nazwa;
}

void Szkola::setNumer(int numer) {
    this->numer = numer;
}

Szkola::Szkola(string nazwa, int numer) {
    this->nazwa = nazwa;
    this->numer = numer;
}

string Szkola::getNazwa() {
    return nazwa;
}

int Szkola::getNumer() {
    return numer;
}

void Szkola::getKlasy() {
    for(int i = 0 ; i < klasy.size();i++){
        cout<<"Klasy :"<<"\n"<<klasy[i]->getNumer()<<"\n";
    }
}

void Szkola::dodajKlase(Klasa* klasa) {
    klasy.push_back(klasa);
}

void Szkola::usunKlase(int numer) {
    for(int i = 0 ; i < klasy.size();i++){
        if(i == numer){
            klasy.erase(klasy.begin()+i);
        }
    }
}
