//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Szkola.h
//  @ Date : 08.04.2024
//  @ Author :
//
//

#include <string>
#include <vector>
using namespace std;
#include "Klasa.h"
#if !defined(_SZKOLA_H)
#define _SZKOLA_H


class Szkola {
public:
	void setNazwa(string nazwa);
	void setNumer(int numer);
	Szkola(string nazwa, int numer);
	string getNazwa();
	int getNumer();
	void getKlasy();
	void dodajKlase(Klasa* klasa);
	void usunKlase(int numer);
private:
	string nazwa;
	int numer;
	vector<Klasa*> klasy;
};

#endif  //_SZKOLA_H
