//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczen.h
//  @ Date : 08.04.2024
//  @ Author :
//
//

#include <string>
using namespace std;
#if !defined(_UCZEN_H)
#define _UCZEN_H


class Uczen {
public:
	void setImie(string imie);
	void setNazwisko(string nazwisko);
	void setWiek(int wiek);
	void setIndex(int id);
	string getImie();
	string getNazwisko();
	int getWiek();
	int getId();
	Uczen(string imie,string nazwisko, int wiek,int index);
private:
	string imie;
	string nazwisko;
	int wiek;
	int index;
};

#endif  //_UCZEN_H
