//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczen.cpp
//  @ Date : 08.04.2024
//  @ Author :
//
//


#include "Uczen.h"

void Uczen::setImie(string imie) {
    this->imie = imie;
}

void Uczen::setNazwisko(string nazwisko) {
    this->nazwisko = nazwisko;
}

void Uczen::setWiek(int wiek) {
    this->wiek = wiek;
}

void Uczen::setIndex(int id) {
    this->index = id;
}

string Uczen::getImie() {
    return imie;
}

string Uczen::getNazwisko() {
    return nazwisko;
}

int Uczen::getWiek() {
    return wiek;
}

int Uczen::getId() {
    return index;
}
Uczen::Uczen(string imie,string nazwisko,int numer,int index) {
    this->imie = imie;
    this->nazwisko = nazwisko;
    this->wiek = numer;
    this->index = index;
}
