//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pacjent.cpp
//  @ Date : 19.03.2024
//  @ Author :
//
//


#include "Pacjent.h"
#include <string>
using namespace std;

Pacjent::Pacjent(int id, string imie, string nazwisko, int wiek) {
    this->idPacjenta = id;
    this->imie = imie;
    this->nazwisko = nazwisko;
    this->wiek = wiek;
}

int Pacjent::getId() {
    return idPacjenta;
}

string Pacjent::getImie() {
    return imie;
}

string Pacjent::getNazwisko() {
    return nazwisko;
}

int Pacjent::getWiek() {
    return wiek;
}

