//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pacjent.h
//  @ Date : 19.03.2024
//  @ Author :
//
//


#if !defined(_PACJENT_H)
#define _PACJENT_H
#include <string>
using namespace std;

class Pacjent {
public:
	Pacjent(int id, string imie, string nazwisko, int wiek);
	int getId();
	string getImie();
	string getNazwisko();
	int getWiek();
private:
	int idPacjenta;
	string imie;
	string nazwisko;
	int wiek;
};

#endif  //_PACJENT_H
