//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Szpital.h
//  @ Date : 19.03.2024
//  @ Author :
//
//


#if !defined(_SZPITAL_H)
#define _SZPITAL_H
#include <string>
#include "Pacjent.h"
#include <vector>
using namespace std;

class Szpital {
public:
	void dodajPacjenta(Pacjent* pacjent);
	void usunPacjenta(int idPacjenta);
	void getPacjenci();
	Szpital(string nazwa);
private:
	string nazwaSzpitala;
	vector<Pacjent*>pacjenci;
};

#endif  //_SZPITAL_H
