//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kierowca.h
//  @ Date : 18.03.2024
//  @ Author :
//
//


#if !defined(_KIEROWCA_H)
#define _KIEROWCA_H
#include <string>
#include <vector>
using namespace std;
#include "Samochod.h"

class Samochod;
class Kierowca {
public:
	Kierowca(string imie, string nazwisko);
	void dodajSamochod(Samochod* samochod);
	void getSamochody();
	string getImie();

private:
	string imie;
	string nazwisko;
	vector<Samochod*> samochody;
};

#endif  //_KIEROWCA_H
