//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kierowca.cpp
//  @ Date : 18.03.2024
//  @ Author :
//
//

#include <string>
using namespace std;
#include <vector>
#include "Kierowca.h"
#include "Samochod.h"
#include <iostream>

Kierowca::Kierowca(string imie, string nazwisko) {
    this->imie = imie;
    this->nazwisko = nazwisko;
}
string Kierowca::getImie(){
    return imie;
}
void Kierowca::dodajSamochod(Samochod* samochod) {
    samochody.push_back(samochod);
    cout<<"Pomyslnie dodano samochod\n";
}
void Kierowca::getSamochody(){
    cout<<"\nSamochody uzytkownika "<<this->getImie()<<"\n";
    for(int i = 0 ; i <samochody.size();i++){
        cout<<samochody[i]->getMarka()<<"|"<<samochody[i]->getModel()<<"\n";
    }
}

