//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Samochod.h
//  @ Date : 18.03.2024
//  @ Author :
//
//

#include <string>
using namespace std;
#if !defined(_SAMOCHOD_H)
#define _SAMOCHOD_H
#include "Kierowca.h"

class Kierowca;
class Samochod {
public:
	void dodajKierowce(Kierowca* kierowca);
	Samochod(string marka, string model);
	string getMarka();
	string getModel();
private:
	string marka;
	string model;
	Kierowca* kierowca;
};

#endif  //_SAMOCHOD_H
