//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Samochod.cpp
//  @ Date : 18.03.2024
//  @ Author :
//
//

#include <string>
using namespace std;
#include "Samochod.h"
#include "Kierowca.h"

void Samochod::dodajKierowce(Kierowca* kierowca) {
    this->kierowca = kierowca;
}

Samochod::Samochod(string marka, string model) {
    this->marka = marka;
    this->model = model;
}
string Samochod::getMarka(){
    return marka;
}
string Samochod::getModel(){
    return model;
}

