//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KomisSamochodowy.h
//  @ Date : 08.04.2024
//  @ Author :
//
//



#if !defined(_KOMISSAMOCHODOWY_H)
#define _KOMISSAMOCHODOWY_H

#include <string>
using namespace std;
#include<vector>
#include "Samochod.h"

class KomisSamochodowy {
public:
	void dodajSamochod(Samochod* samochod);
	void usunSamochod(int id);
	void getSamochody();
	KomisSamochodowy(string nazwa, string adres);
private:
	string nazwa;
	string adres;
	vector<Samochod*> samochody;
};

#endif  //_KOMISSAMOCHODOWY_H
