//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pojazd.h
//  @ Date : 08.04.2024
//  @ Author :
//
//

#include <string>
using namespace std;
#if !defined(_POJAZD_H)
#define _POJAZD_H


class Pojazd {
public:
	void setRodzaj(string rodz);
	void setSrodowisko(string srodowisko);
	string getRodzaj();
	string getSrodowisko();
private:
	string rodzajPojazdu;
	string srodowiskoUzytku;
};

#endif  //_POJAZD_H
