//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pojazd.cpp
//  @ Date : 08.04.2024
//  @ Author :
//
//

#include <string>
using namespace std;
#include "Pojazd.h"


void Pojazd::setRodzaj(string rodz) {
    this->rodzajPojazdu = rodz;
}

void Pojazd::setSrodowisko(string srodowisko) {
    this->srodowiskoUzytku = srodowisko;
}

string Pojazd::getRodzaj() {
    return rodzajPojazdu;
}

string Pojazd::getSrodowisko() {
    return srodowiskoUzytku;
}

