//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Samochod.cpp
//  @ Date : 08.04.2024
//  @ Author :
//
//

#include <string>
using namespace std;
#include "Samochod.h"


int Samochod::getMoc() {
    return moc;
}

string Samochod::getMarka() {
    return marka;
}

string Samochod::getModel() {
    return model;
}

Samochod::Samochod(string Marka, string Model, int Moc) {
    this->marka = Marka;
    this->model = Model;
    this->moc = Moc;
}

void Samochod::setModel(string model) {
    this->model = model;
}

void Samochod::setMarka(string marka) {
    this->marka = marka;
}

void Samochod::setMoc(int moc) {
    this->moc = moc;
}

