//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Samochod.h
//  @ Date : 08.04.2024
//  @ Author :
//
//
#include <string>
using namespace std;
#include<iostream>
#if !defined(_SAMOCHOD_H)
#define _SAMOCHOD_H

#include "Pojazd.h"

class Samochod : public Pojazd {
public:
	string getMarka();
	string getModel();
	int getMoc();
	Samochod(string marka, string model, int moc);
	void setModel(string model);
	void setMarka(string marka);
	void setMoc(int moc);
private:
	string marka;
	string model;
	int moc;
};

#endif  //_SAMOCHOD_H
