//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Firma.cpp
//  @ Date : 18.03.2024
//  @ Author :
//
//


#include <string>
using namespace std;
#include "Firma.h"
#include<iostream>

void Firma::dodajPracownika(Pracownik* pracownik) {
    int przedDodaniem = pracownicy.size();
    pracownicy.push_back(pracownik);
    if (pracownicy.size() > przedDodaniem) {
        std::cout << "Udalo sie dodac pracownika." << std::endl;
    } else {
        std::cout << "Nie udalo sie dodac pracownika." << std::endl;
    }
}

void Firma::usunPracownika(int idPracownika) {
    for (int i = 0; i < pracownicy.size(); ++i) {
        if (idPracownika == pracownicy[i]->getIdPracownika()) {
            pracownicy.erase(pracownicy.begin() + i);
            std::cout << "Usunieto pracownika o ID: " << idPracownika << std::endl;
            return;
        }
    }
    std::cout << "Nie znaleziono pracownika o ID: " << idPracownika << std::endl;
}



Firma::Firma(string nazwa, int rokZalozenia) {
    this->nazwa = nazwa;
    this->rokZalozenia = rokZalozenia;
}

void Firma::getPracownicy() {
    for (int i = 0 ; i<pracownicy.size();i++){
        cout<<pracownicy[i]->getIdPracownika()<<" | "<<pracownicy[i]->getImie()<<" | "<<pracownicy[i]->getNazwisko()<<"\n";
    }
}


