//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Firma.h
//  @ Date : 18.03.2024
//  @ Author :
//
//


#if !defined(_FIRMA_H)
#define _FIRMA_H
#include <string>
using namespace std;
#include "Pracownik.h"
#include <vector>


class Firma {
public:
	void dodajPracownika(Pracownik* pracownik);
	void usunPracownika(int idPracownika);
	Firma(string nazwa, int rokZalozenia);
	void getPracownicy();
private:
	string nazwa;
	int rokZalozenia;
	vector<Pracownik*> pracownicy;
};

#endif  //_FIRMA_H
