//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.h
//  @ Date : 18.03.2024
//  @ Author :
//
//


#if !defined(_PRACOWNIK_H)
#define _PRACOWNIK_H
#include <string>
using namespace std;


class Pracownik {
public:
	Pracownik(string imie, string nazwisko,int idPracownika);
	string getImie();
	string getNazwisko();
	int getIdPracownika();
private:
	string imie;
	string nazwisko;
	int idPracownika;
};

#endif  //_PRACOWNIK_H
