//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Paliwo.h
//  @ Date : 18.03.2024
//  @ Author :
//
//


#if !defined(_PALIWO_H)
#define _PALIWO_H
#include <string>
using namespace std;

class Paliwo {
public:
	Paliwo(string nazwa, string rodzaj, int liczbaOktanowa);
	void setNazwa(string nazwa);
	void setRodzaj(string rodzaj);
	void setLiczbaOktanowa(int oktany);
	string getNazwa();
	string getRodzaj();
	int getLiczbaO();
private:
	string nazwa;
	string rodzaj;
	int liczbaOktanowa;
};

#endif  //_PALIWO_H
