//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Samochod.cpp
//  @ Date : 18.03.2024
//  @ Author :
//
//


#include "Samochod.h"
#include "Paliwo.h"
#include <string>
#include <iostream>
using namespace std;

Samochod::Samochod(string marka, string model, string rodzaj, int rok) {
    this->marka = marka;
    this->model = model;
    this->rodzajPaliwa = rodzaj;
    this->rokProdukcji = rok;
}

void Samochod::setMarka(string marka) {
    this->marka = marka;
}

void Samochod::setModel(string model) {
    this->model = model;
}

void Samochod::setRodzaj(string rodzaj) {
    this->rodzajPaliwa = rodzaj;
}

string Samochod::getMarka() {
    return marka;
}

string Samochod::getModel() {
    return model;
}

string Samochod::getRodzaj() {
    return rodzajPaliwa;
}

int Samochod::getRok() {
    return rokProdukcji;
}

void Samochod::wyrusz(Paliwo *paliwo) {
    if(paliwo->getRodzaj() == this->getRodzaj()){
        cout<<"Dobre paliwo! Samochod odpalil\n";
    }
    else{
        cout<<"Zle paliwo. Zatarles silnik\n";
    }
}

