//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Samochod.h
//  @ Date : 18.03.2024
//  @ Author :
//
//


#if !defined(_SAMOCHOD_H)
#define _SAMOCHOD_H

#include "Paliwo.h"
#include <string>
using namespace std;

class Samochod {
public:
	Samochod(string marka, string model, string rodzaj, int rok);
	void setMarka(string marka);
	void setModel(string model);
	void setRodzaj(string rodzaj);
	string getMarka();
	string getModel();
	string getRodzaj();
	int getRok();
	void wyrusz(Paliwo *paliwo);
private:
	string marka;
	string model;
	string rodzajPaliwa;
	int rokProdukcji;
};

#endif  //_SAMOCHOD_H
