//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.h
//  @ Date : 12.03.2024
//  @ Author :
//
//


#if !defined(_JAMNIK_H)
#define _JAMNIK_H
#include <string>
#include "Pies.h"
using namespace std;

class Jamnik : public Pies {
public:
	void setNazwa(string nazwa);
	void setKolor(string nazwa);
	string getNazwa();
	string getKolor();
	void szczeknij();
	Jamnik(string name, string kolor);
private:
	string nazwa;
	string kolor;
};

#endif  //_JAMNIK_H
