//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 12.03.2024
//  @ Author :
//
//

#include <string>
#include "Jamnik.h"
#include <iostream>

using namespace std;

void Jamnik::setNazwa(string nazwa) {
    this->nazwa = nazwa;
}

void Jamnik::setKolor(string nazwa) {
    this->kolor = nazwa;
}

string Jamnik::getNazwa() {
    return nazwa;
}

string Jamnik::getKolor() {
    return kolor;
}

void Jamnik::szczeknij() {
    cout<<"hau hau";
}

Jamnik::Jamnik(string name, string kolor) {
    this->nazwa = name;
    this->kolor = kolor;
}

