//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 12.03.2024
//  @ Author :
//
//


#if !defined(_PIES_H)
#define _PIES_H
#include <string>
#include "Ssak.h"
using namespace std;

class Pies : public Ssak {
public:
	void setRasa(string rasa);
	void setWiek(int wiek);
	string getRasa();
	int getWiek();
private:
	string rasa;
	int wiek;
};

#endif  //_PIES_H
