//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 12.03.2024
//  @ Author :
//
//

#include <string>
#include "Pies.h"
using namespace std;

void Pies::setRasa(string rasa) {

}

void Pies::setWiek(int wiek) {

}

string Pies::getRasa() {

}

int Pies::getWiek() {

}

