//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 12.03.2024
//  @ Author :
//
//

#include <string>
#include "Ssak.h"
using namespace std;

void Ssak::setNazwa(string nazwa) {

}

void Ssak::setSrodowisko(string srodowisko) {

}

string Ssak::getNazwa() {

}

string Ssak::getSrodowisko() {

}

