//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 12.03.2024
//  @ Author :
//
//


#if !defined(_SSAK_H)
#define _SSAK_H
#include <string>
using namespace std;

class Ssak {
public:
	void setNazwa(string nazwa);
	void setSrodowisko(string srodowisko);
	string getNazwa();
	string getSrodowisko();
private:
	string nazwa_ssaka;
	string srodowisko_wystepowania;
};

#endif  //_SSAK_H
