//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Program.cpp
//  @ Date : 08.04.2024
//  @ Author :
//
//

#include <string>
using namespace std;
#include "Program.h"
#include "Watek.h"

string Program::getNazwa() {
    return nazwa;
}

int Program::getWatekId() {
    return watek->getId();
}

Program::Program(string nazwa) {
    this->nazwa = nazwa;
    watek = new Watek(0);
}
Program::~Program() {
    delete watek;
}
