//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Watek.h
//  @ Date : 08.04.2024
//  @ Author :
//
//


#if !defined(_WATEK_H)
#define _WATEK_H


class Watek {
public:
	int getId();
	Watek(int id);
private:
	int id;
};

#endif  //_WATEK_H
