//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Watek.cpp
//  @ Date : 08.04.2024
//  @ Author :
//
//

#include "Watek.h"

int Watek::getId() {
    return id;
}

Watek::Watek(int id) {
    this->id = id;
}
