//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : System.cpp
//  @ Date : 09.04.2024
//  @ Author :
//
//
#include <iostream>
#include <vector>
#include <string>
#include "Uzytkownik.h"
using namespace std;
#include "System.h"

bool System::uwierzytelnij(string login,string haslo) {
    for(int i = 0 ; i < uzytkownicy.size();i++){
        if(uzytkownicy[i]->getLogin() == login && uzytkownicy[i]->getHaslo() == haslo){
            return true;
        }
    }

    return false;
}

void System::dodajUser(Uzytkownik* user){
    uzytkownicy.push_back(user);
}

