//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : System.h
//  @ Date : 09.04.2024
//  @ Author :
//
//


#if !defined(_SYSTEM_H)
#define _SYSTEM_H


#include <vector>
#include <string>
#include "Uzytkownik.h"
using namespace std;

class Uzytkownik;
class System {
public:
	vector<Uzytkownik*> tab;
	bool uwierzytelnij(string login);
	void dodajUser(Uzytkownik* user);
};

#endif  //_SYSTEM_H
