//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : System.cpp
//  @ Date : 09.04.2024
//  @ Author :
//
//
#include <iostream>
#include <vector>
#include <string>
#include "Uzytkownik.h"
using namespace std;
#include "System.h"

bool System::uwierzytelnij(string login) {
    for(int i = 0 ; i < tab.size();i++){
        if(tab[i]->getLogin() == login){
            return true;
        }
    }

    return false;
}

void System::dodajUser(Uzytkownik* user) {
    if(!this->uwierzytelnij(user->getLogin())){
        tab.push_back(user);
    }
}

