//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.h
//  @ Date : 09.04.2024
//  @ Author :
//
//


#if !defined(_UZYTKOWNIK_H)
#define _UZYTKOWNIK_H

#include <string>
using namespace std;
#include "System.h"

class System;
class Uzytkownik {
public:
	Uzytkownik(string login, string password);
	void rejestruj(System* sys_pointer, Uzytkownik *User);
	void loguj(System* sys_pointer);
	void wyloguj();
	string getLogin();
	string getHaslo();
private:
	string login;
	string haslo;
	System* s_pointer;
};

#endif  //_UZYTKOWNIK_H
