//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernouli.h
//  @ Date : 22.04.2024
//  @ Author :
//
//


#if !defined(_BERNOULI_H)
#define _BERNOULI_H
#include "Potega.h"
#include "SymbolNewtona.h"


class Bernouli {
public:
	Bernouli();
	long double obliczWyniki(int n,int k, long double p);
	~Bernouli();
private:
	Potega* potega;
	SymbolNewtona* symbol;
};

#endif  //_BERNOULI_H
