//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Potega.h
//  @ Date : 22.04.2024
//  @ Author :
//
//


#if !defined(_POTEGA_H)
#define _POTEGA_H


class Potega {
public:
	long double wynikPotegi(long double pod,int wyk);
	Potega();
	~Potega();
};

#endif  //_POTEGA_H
