//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.h
//  @ Date : 22.04.2024
//  @ Author :
//
//


#if !defined(_SILNIA_H)
#define _SILNIA_H


class Silnia {
public:
	Silnia();
	long int wynikSilnii(int x);
	~Silnia();
};

#endif  //_SILNIA_H
