//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.cpp
//  @ Date : 22.04.2024
//  @ Author :
//
//

#include <iostream>
#include "Silnia.h"
using namespace std;
Silnia::Silnia() {
    //cout<<"konstruktor silnii";
}

long int Silnia::wynikSilnii(int x) {
    int i = 1;
    int silnia= 1;
    while(i<=x){
         silnia*=i;
         i+=1;
    }
    return silnia;
}

Silnia::~Silnia() {
    //cout<<"Destruktor Silnii";
}

