//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SymbolNewtona.cpp
//  @ Date : 22.04.2024
//  @ Author :
//
//

#include <iostream>
#include "SymbolNewtona.h"
using namespace std;
long double SymbolNewtona::wynikNewtona(int n, int k) {
    return silnia->wynikSilnii(n)/(silnia->wynikSilnii(k)* silnia->wynikSilnii(n-k));
}

SymbolNewtona::SymbolNewtona() {
    this->silnia = new Silnia();
}

SymbolNewtona::~SymbolNewtona() {
    delete silnia;
    //cout<<"destruktor silnii \n";
}

