//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SymbolNewtona.h
//  @ Date : 22.04.2024
//  @ Author :
//
//


#if !defined(_SYMBOLNEWTONA_H)
#define _SYMBOLNEWTONA_H
#include "Silnia.h"

class SymbolNewtona {
public:
	long double wynikNewtona(int n, int k);
	SymbolNewtona();
	~SymbolNewtona();
private:
	Silnia* silnia;
};

#endif  //_SYMBOLNEWTONA_H
